name: Action Build - CI
on:
  push:
    branches: [master]

jobs:
  test-ci:
    runs-on: ubuntu-latest
    name: Test Build Universal APK - remote
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download test keystore file
        uses: wei/wget@v1
        with: 
          args: -O keystore.jks https://github.com/skywall/universal-apk-builder/blob/master/test/keystore.jks?raw=true
      - name: Download test AAB file
        uses: wei/wget@v1
        with: 
          args: -O app.aab https://github.com/skywall/universal-apk-builder/blob/master/test/app-release.aab?raw=true
      - name: "Build Universal APK"
        uses: skywall/universal-apk-builder@master
        with:
          aab_path: "app.aab"
          output_dir: "output"
          keystore_path: "keystore.jks"
          keystore_password: "android"
          keystore_alias: "androiddebugkey"
          keystore_alias_password: "android"
      - name: "Check APK patch exists"
        if: ${{ env.UNIVERSAL_APK_PATH != 'output/universal.apk' }} 
        run: |
          echo "Path not as expected ('output/universal.apk'): '${{ env.UNIVERSAL_APK_PATH }}'"
          exit 1
